# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "spotify-debian-squeeze-64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = ""

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.15"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder  '.', '/vagrant', :nfs => true

  # Spotify Plugin Puppet config
  #config.spotify.puppet_verbose = true
  #config.spotify.puppet_debug   = true
  #config.spotify.puppet_path    = '../spotify-puppet'
  #config.spotify.puppet_modules = ['vagrant/puppet/modules']
  #config.spotify.puppet_classes = ['apache']

  # Enable Spotify provisioner
  #config.vm.provision :spotify

  # Puppet standalone provisioner
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "vagrant/puppet/modules"
    puppet.manifests_path = "vagrant/puppet/manifests"
    puppet.manifest_file  = "init.pp"
    puppet.options = "--verbose --debug"
  end

end